// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://2y4lpwdqebbpfadqp2fs5likum.appsync-api.eu-north-1.amazonaws.com/graphql',
          region: 'eu-north-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-toncrli6jjdalhwggo4hpvfpqm'
        }
    }
};

export default config;